1. What is a Python library? Why do we use Python libraries?


2. What is the difference between Numpy array and List?


3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?


8. Describe the difference between np.random.rand and np.random.randn?

 

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python
Index wise multiplicatio
Matrix multiplicatio
Add both the matric
Subtract matrix B from
Divide Matrix B by A


12. Which function in Numpy can be used to swap the byte order of an array?

13. What is the significance of the np.linalg.inv function?

14. What does the np.reshape function do, and how is it used?

15. What is broadcasting in Numpy?


#1. What is a Python library? Why do we use Python libraries?
Python library contain predefined functions and modules that are optmized.
we can use those fuctions once we import those modules and these fuctions can reusable in our code.
pre-written codes and modules are optimized hence time taken to execute those fuctions are less,efficient.

#2. What is the difference between Numpy array and List?
NUMPY ARRAY:numpy array is collection of homogeneous elements,means same type of data will store in array.
    Numpy arrays are faster becuase of it contain homogeneous elements hence faster access is there,data stores in     contigious memory location.
    Numpy arrays are static.List are dymamic,List stores heterogenous elements,means stores different type of         elements of different locations.List is slower than Numpy array.
    In Numpy arrays Vectorisation is there .add,multiply element by element.

"""3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]"""

In [10]:
import numpy as np
a=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a.size

12

In [13]:
a.shape

(3, 4)

In [14]:
a.ndim

2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1[1]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [22]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2[2,3]

12

In [21]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3[1::2]

array([[5, 6, 7, 8]])

In [26]:
arr4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4[::2,1::2]

array([[ 2,  4],
       [10, 12]])

In [30]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
np.random.random(size=(3,3))

array([[0.63903269, 0.80775091, 0.4156966 ],
       [0.68131424, 0.73848795, 0.78585088],
       [0.25034372, 0.07147256, 0.86074095]])

In [34]:
#8. Describe the difference between np.random.rand and np.random.randn?
np.random.rand(10)
#Generates random numbers from a uniform distribution over the interval [0, 1).
#All values have an equal probability of being selected within this range.

array([0.29129584, 0.17083918, 0.92342546, 0.33371222, 0.3891881 ,
       0.63844881, 0.66026214, 0.88103036, 0.69312115, 0.78952906])

In [32]:
np.random.randn(10)
#Generates random numbers from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1.
#The numbers can be positive or negative, and most will fall between -1 and 1, with fewer outliers.

array([-1.72854902, -0.07747418,  0.13730231,  0.16192742, -0.67185143,
        2.1523177 ,  0.20704159, -2.92117891,  0.4505811 , -1.78055604])

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [37]:
arr4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.expand_dims(arr4,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [38]:
arr5=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr5.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python
Index wise multiplicatio
Matrix multiplicatio
Add both the matric
Subtract matrix B from
Divide Matrix B by A

In [39]:
arr6=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr7=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [40]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr6*arr7

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [54]:
arr6@arr7 #not possible because n*m p*q where m!=p

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [46]:
arr6+arr7

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [47]:
arr6-arr7

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
arr6/arr7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
#12. Which function in Numpy can be used to swap the byte order of an array?
#using byteswap
a=np.array([1,2,3,4])
print(a)
b=a.byteswap(inplace=False)
c=a.byteswap(inplace=True)
print(b)
print(c)

[1 2 3 4]
[ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744]
[ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744]


In [58]:
import numpy as np

# Creating a numpy array
arr = np.array([1, 256, 4096], dtype=np.int16)

# Display the original array and its byte order
print("Original array:", arr)
print("Original byte order:", arr.byteswap(inplace=False))

# Swap the byte order
arr.byteswap(inplace=True)

# Display the array after swapping byte order
print("Array after byte swap:", arr)


Original array: [   1  256 4096]
Original byte order: [256   1  16]
Array after byte swap: [256   1  16]


In [59]:
#13. What is the significance of the np.linalg.inv function?
import numpy as np

# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

# Display the result
print("Original matrix:\n", matrix)
print("Inverse matrix:\n", inverse_matrix)

# Verify the result (matrix multiplied by its inverse should be the identity matrix)
print("Matrix * Inverse matrix:\n", np.dot(matrix, inverse_matrix))


Original matrix:
 [[1 2]
 [3 4]]
Inverse matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix * Inverse matrix:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#14. What does the np.reshape function do, and how is it used?
The np.reshape() function in NumPy is used to change the shape of an existing array without altering its data. This function allows you to specify new dimensions (rows, columns, etc.) for the array while keeping the original data intact.
The total number of elements in the new shape must be equal to the total number of elements in the original array.
You can use -1 as a placeholder in one of the dimensions to let NumPy automatically calculate that dimension.

In [61]:
arr8=np.array([[1,2,3,4]])
print(arr8)
arr9=np.reshape(arr8,(2,2))
print(arr9)

[[1 2 3 4]]
[[1 2]
 [3 4]]


#15. What is broadcasting in Numpy?
When performing operations on arrays of different shapes, NumPy compares their dimensions. If the shapes are compatible, it broadcasts the smaller array across the larger array so that the operation can be performed element-wise.

In [62]:
arr=np.array([1,2,3,4])
arr+5

array([6, 7, 8, 9])

In [65]:
arr10=arr+np.array([[3,4,5,6],[2,3,4,5]])
print(arr10)

[[ 4  6  8 10]
 [ 3  5  7  9]]
